Enable LTO in Rust release profile
drasi-project/drasi-core pull request #32
Opened 2024-10-28 18:49 UTC by ruokun-niu

# Description

Enabling Link Time Optimization (LTO) will reduce the binary size. By setting `lto` to be `true` in the release profile, LTO will only be enabled in our release build, as we use the command `cargo install` in our dockerfiles. When we do a local `cargo build`, LTO will not be enabled. To enable LTO in `cargo build`, run with the `--release` flag

Results from running the `query-perf` tests with and without LTO: 
Without LTO:  https://gist.github.com/ruokun-niu/70c0252f4a36bdf5f4d52febf35a9226
With LTO: https://gist.github.com/ruokun-niu/08de253ef74ae4b6fede0effcb695b48

## Type of change

- This pull request fixes a bug in Drasi and has an approved issue (issue link required).
- This pull request adds or changes features of Drasi and has an approved issue (issue link required).
- This pull request is a minor refactor, code cleanup, test improvement, or other maintenance task and doesn't change the functionality of Drasi (issue link optional).

Fixes: [#97](https://github.com/drasi-project/drasi-platform/issues/97)

2024-10-28 23:40 UTC, danielgerlag approved these changes

2024-11-08 14:44 UTC, agentofreality requested changes

2024-11-08 14:44 UTC, agentofreality commented on query-perf/README.md
> +./run_perf_tests.sh
@ruokun-niu this change is not correct. This text talks about running the component test tool in general, this script just runs the tool using our set of pre-configured tests. Need to revert.

2025-01-15 04:09 UTC, agentofreality submitted a review, later dismissed

2025-06-20 21:19 UTC, ruokun-niu commented
@danielgerlag @agentofreality @amansinghoriginal  This is PR is ready to be reviewed again. All checks have passed.

Thanks

2025-06-20 21:37 UTC, danielgerlag approved these changes

2025-06-25 06:34 UTC, amansinghoriginal reviewed
Looks like the two other files (README.md and run_perf_tests) have no functional changes.

Are these changes needed?

2025-06-25 06:34 UTC, amansinghoriginal commented on query-perf/README.md
> +- rocksdb
no-change?

2025-06-25 06:34 UTC, amansinghoriginal commented on query-perf/run_perf_tests
> +
is there no change in this file? just permissions change?

2025-06-25 16:16 UTC, ruokun-niu commented
> Looks like the two other files (README.md and run_perf_tests) have no functional changes.
> 
> Are these changes needed?

I don't think there are any changes.

2025-06-25 16:22 UTC, ruokun-niu commented
@amansinghoriginal  I have cleaned up the commit history

2025-06-26 21:13 UTC, amansinghoriginal approved these changes
Thanks for this change.

2025-06-26 21:15 UTC, danielgerlag approved these changes

2025-06-26 21:43 UTC, merged